### ISSUE TITLE
Feature request: option to auto paste emoji after choosing it

### ISSUE THREAD

**Issue by AXeL-dev** [Ulauncher/ulauncher-emoji#11]
I would love to see an auto paste feature, like in many others emoji selectors.

@MyriaCore Could you help on implementing this feature on your fork please? I'm not sure if it's doable, what do you think?

**Comment by MyriaCore** [comment]
I was thinking about this too. In the past, I've used [xdotool](https://github.com/jordansissel/xdotool) for things like this. Maybe it'd be possible to use a [shell subprocess](https://stackoverflow.com/a/9682073) and call it?

I could provide assistance, but I'm trying to pull back from open source and personal projects because of university, which gobbles up like 110% of my free time lol

**Comment by MyriaCore** [comment]
Could also be possible to copy and then insert by putting the copy action and the insert action in an [Action List](https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher/api/shared/action/ActionList.py).

Regardless, it's probably doable.

**Comment by AXeL-dev** [comment]
> I was thinking about this too. In the past, I've used [xdotool](https://github.com/jordansissel/xdotool) for things like this. Maybe it'd be possible to use a [shell subprocess](https://stackoverflow.com/a/9682073) and call it?

In fact i'm using a Clipboard Manager called [Clipped](https://github.com/davidmhewitt/clipped) which already has this feature. & from [sources](https://github.com/davidmhewitt/clipped/blob/b00d44757cc2bf7bc9948d535668099db4ab9896/src/ClipboardManager.vala#L55) i think that it use fake events same as xdotool.

**Comment by AXeL-dev** [comment]
I figured out that the XTest library used in Clipped is available on python too:

- [pypi link](https://pypi.org/project/xtest)
- [github link](https://github.com/sorenh/python-xtest)

So we could maybe use it instead of calling xdotool using a subprocess?

**Comment by MyriaCore** [comment]
Sure, if u think it'll be faster. xdotool was just the one I thought of, plus it does character encoding for typing simulations I think, so it's not JUST sending shift-insert. 

Regardless, I think it'll just be cool that it's working lol. Lmk how it works out! I'll be here if u need help with the implementation

**Comment by AXeL-dev** [comment]
@MyriaCore I think that creating a custom action didn't work since i'm getting the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/utils/SimpleWebSocketServer.py", line 574, in _parseMessage
    self._handlePacket()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/SimpleWebSocketServer.py", line 245, in _handlePacket
    self.handleMessage()
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionController.py", line 70, in handleMessage
    response = pickle.loads(self.data)
AttributeError: Can't get attribute 'PasteAction' on <module '__main__' from '/usr/bin/ulauncher'>
```

So, what do you suggest? have i done something wrong?

**Comment by AXeL-dev** [comment]
Finally got it to work, based on code from [ulauncher-kill](https://github.com/Ulauncher/ulauncher-kill/blob/master/main.py) extension.

**Comment by MyriaCore** [comment]
Sweet! Yeah, the custom actions seem kinda fiddly. Glad you figured it out!

**Comment by MyriaCore** [comment]
There are still some users who might want to *just* copy the emoji, so it might be wise to add an action setting in the settings. Maybe the user could choose from "Auto-Insert" or "Copy".

**Comment by MyriaCore** [comment]
Nice! Just checked out your code. I think instead of sending `Ctrl-V`, u should send `Shift-Insert`, since some applications won't accept `Ctrl-V` (like terminals).

**Comment by MyriaCore** [comment]
any updates?

**Comment by AXeL-dev** [comment]
> any updates @AXeL-dev?

Well i didn't rework on this since the last time. I'll try to this night.

**Comment by AXeL-dev** [comment]
@MyriaCore  it seems like pasting emojis using `Shift-Insert` doesn't work on my terminal app (Tilix), it pastes only the last copied textual value, but it works weirdly using paste option of the mouse right click menu.

![image](https://user-images.githubusercontent.com/30635693/94014760-e31c4a00-fda3-11ea-82ff-c30d3655558f.png)

**Comment by MyriaCore** [comment]
Maybe instead of copying into the clipboard, we should copy into the primary buffer? I think `Shift-Insert` might be for the primary buffer, although I'm not sure. Middle click also pastes the primary buffer.

**Comment by MyriaCore** [comment]
The `CopyToClipboardAction` is defined [here](https://github.com/Ulauncher/Ulauncher/blob/4833e779332ac1a439e3fce1f96af684214683b8/ulauncher/api/shared/action/CopyToClipboardAction.py#L22-L25).

After looking at [relevant](https://developer.gnome.org/pygtk/unstable/class-gdkatom.html) [docs](https://developer.gnome.org/gtk3/stable/gtk3-Clipboards.html#gtk-clipboard-get), it looks like maybe we could use the following to make `Shift-Insert` work:

```python
class CopyToPrimaryClipboardAction(CopyToClipboardAction):
    """
    Copy text to the clipboard
    :param str text: text to copy
    """
    def run(self):
        clipboard = Gtk.Clipboard.get(Gdk.SELECTION_PRIMARY)
        clipboard.set_text(self.text, -1)
        clipboard.store()
```

**Comment by MyriaCore** [comment]
@AXeL-dev you can test this on your terminal by:

1. selecting something in your terminal
2. immediately `Shift-insert`
3. See the thing you selected in your terminal

Since we use the primary selection instead of the clipboard, shift-insert should basically work everywhere, since AFAIK it's accepted everywhere, since it's more of a system thing than a user-controllable clipboard thing.

**Comment by MyriaCore** [comment]
I've implemented this in [MyriaCore/auto-paste](https://github.com/MyriaCore/ulauncher-emoji/tree/auto-paste).

**Comment by MyriaCore** [comment]
HMMM, still not working. This is super weird.

**Comment by MyriaCore** [comment]
Maybe the primary clipboard is read only? How does `xsel` do it then, cause im pretty sure xsel can copy into the primary clipboard. I mean, the easy way out here could totally be just to subprocess out into `xsel`. 

This is honestly pretty frustrating. Maybe it would've been better if we had just piped out at the beginning.

**Comment by AXeL-dev** [comment]
I guess there should be a way to achieve it, the most common problem in Linux (i mean the one i always face) is the lake of good documentation, especially on some low level libraries.. Anyway, i'll try to give it a look from my side once i get enough free time for.

**Comment by MyriaCore** [comment]
Yeah. IDK, documentation is there, I guess I just don't know as much as I thought about the clipboard system. 

Most of my experience comes from working on [a fork of texpander](https://gitlab.com/myriacore/texpander/-/blob/2e2eff00685c1a028b04703d708136a73530ea24/texpander.sh#L235). Here, Shift-Insert *is* used to paste, and the text content is placed into [the primary buffer](https://gitlab.com/myriacore/texpander/-/blob/2e2eff00685c1a028b04703d708136a73530ea24/texpander.sh#L242) *and* into the [clipboard buffer](https://gitlab.com/myriacore/texpander/-/blob/2e2eff00685c1a028b04703d708136a73530ea24/texpander.sh#L246). 

As I said, worst case we can use xsel to copy, and then use this XTest library to paste. IDK why the gtk clipboard stuff isn't working, but AFAIK that stuff is supposed to be used for implementing copy/paste in GUI apps, so I guess we'd be kinda abusing the feature a bit here.

**Comment by gerardbosch** [comment]
Hi there!

I'd love to implement this feature ❤ Is there any update?

I give my two cents here on what I think is a common use case:
If I get it right from the discussion I understood that the choice is on which clipboard to copy the emoji; or if directly insert it without copying to a clipboard.

IMO, and for my use case, to be really useful it should do both: copy to the X clipboard (the one that pastes with `Ctrl`-`v`) + insert the emoji right after.

**Reason**: Many times you want to insert several times the same emoji, like 👏👏👏 - so you should be able to look for the emoji in the picker **once**, hit `return` to insert, and in the event you want to insert more press `ctrl-vvv...`.

`shift - insert` is not very ergonomic, specially on laptop keyboards as involves more keys like `fn` that are far from home and wrist twisting 😬

What do you think? Hope this helps, cheers!!

**Comment by MyriaCore** [comment]
I haven't worked on this since 2020 so no updates unfortunately. I don't remember if I got this to work or not in [my fork](https://github.com/MyriaCore/ulauncher-emoji/tree/auto-paste). Commits look ok but I never merged it, so I have to assume its at least somewhat not working

Again uni takes up a lot of my time so in general I've taken a step back from open source stuff. If you have experience with python why not take a stab at it yourself?
