### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pedrorvidal** [Ulauncher/ulauncher-emoji#25]
Arch linux, fresh install. 
When trying to install uLauncher emoji addon, got the following error message:

message: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
name: TypeError
stack trace: ```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/preferences_server.py", line 123, in request_listener
    data = json.dumps([route_handler(self, *args)])
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/preferences_server.py", line 289, in extension_add
    ExtensionRunner.get_instance().run(ext_id)
  File "/usr/lib/python3.10/site-packages/ulauncher/modes/extensions/ExtensionRunner.py", line 72, in run
    "VERBOSE": str(int(self.verbose)),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

```

The addon is installed, but remains stopped.

**Comment by JuanVqz** [comment]
> I got an error when trying to install but when copying it this is all I get:
> 
> Message: undefined Error Name: undefined Type: undefined
> 
> Stacktrace:
> 
> ```
> undefined
> ```

same error on my end

**Comment by petrarca-arezzo** [comment]
> I got an error when trying to install but when copying it this is all I get:
> 
> Message: undefined Error Name: undefined Type: undefined
> 
> Stacktrace:
> 
> ```
> undefined
> ```

And also here - same issue for me

**Comment by RedBearAK** [comment]
Same undefined error as everyone else here. New install of Fedora 36.

**Comment by petrarca-arezzo** [comment]
> Same undefined error as everyone else here. New install of Fedora 36.
> 
> Edit: Suddenly after leaving the Ulauncher preferences and coming back, the Emoji extension is installed. And working.

I tried it as well - is now installed. Strange, but might be just an issue of ulauncher not providing the right status (e.g. raising an error when in fact everything was fine?).

**Comment by Abdisalan** [comment]
> 

same thing happened. I get the error and then it installed 🤷

**Comment by anibal-aguila** [comment]
Hi, same here.

Message: undefined
Error Name: undefined
Type: undefined

Stacktrace:
```
undefined
```

❯ python --version
Python 3.10.8

**Comment by its-ag** [comment]
> Hi, same here.
> 
> Message: undefined Error Name: undefined Type: undefined
> 
> Stacktrace:
> 
> ```
> undefined
> ```
> 
> ❯ python --version Python 3.10.8

well, i also got the same issue, is there some python dependencies I need to install ?
